name: E2E test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: yarn install && test
      env: 
        CYPRESS_BASE_URL: 'http://localhost:8080'
        CYPRESS_TEST_AUTH_AUDIENCE: 'https://us-central1-waitress-6bc72.cloudfunctions.net/auth'
        CYPRESS_TEST_AUTH_URL: 'https://waitress.auth0.com/oauth/token'
        CYPRESS_TEST_AUTH_CLIENT_ID: 'VUJXuxrPNlVePh3kIUENEkE9v5B4gKoM'
        CYPRESS_TEST_AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
        CYPRESS_TEST_AUTH_USERNAME: 'e2e-testing@mydomain.com'
        CYPRESS_TEST_AUTH_PASSWORD:  ${{ secrets.TEST_USER_PASSWORD }}
      run: |
        yarn install
        yarn test:e2e --headless
      